---
version: 2.1
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2
  gcp-gcr: circleci/gcp-gcr@0.16.2
executors:
  fastflow-executor:
    docker:
      - image: cimg/python:3.11.3
jobs:
  build_and_deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Export GSA file
          command: |
            echo $GSA_BASE64 | base64 -d > ~/gsa.json
      - cloudrun/init
      - cloudrun/deploy:
          image: asia-east1-docker.pkg.dev/fastflow-ai/fastflow/fastflow-cms:${CIRCLE_SHA1}
          platform: managed
          region: asia-east1
          service-name: fastflow-cms
          unauthenticated: true
workflows:
  version: 2
  build_and_deploy_to_managed_workflow:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: fastflow/fastflow-cms
          executor: fastflow-executor
          remote-docker-version: default
          registry-url: asia-east1-docker.pkg.dev
          setup-remote-docker: true
          use-docker-layer-caching: true
          tag: latest,${CIRCLE_SHA1}
          filters:
            branches:
              only:
                - main
      - build_and_deploy:
          requires:
            - gcp-gcr/build-and-push-image

